// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYOBYSBK4ooA-oygV50V9bZA6gW5h9w0',
    appId: '1:855172919590:web:19e3f7108d712f49dd51e7',
    messagingSenderId: '855172919590',
    projectId: 'inventory-4fd72',
    authDomain: 'inventory-4fd72.firebaseapp.com',
    storageBucket: 'inventory-4fd72.firebasestorage.app',
    measurementId: 'G-QVPJ16TYHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBC4uxgwTakhS-Qk5MBQ-eV6GAIt0bsBM',
    appId: '1:855172919590:android:9142ba518191d728dd51e7',
    messagingSenderId: '855172919590',
    projectId: 'inventory-4fd72',
    storageBucket: 'inventory-4fd72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGw3ZZbfDs4Ke4WeHVXiXrK65J493NWw',
    appId: '1:855172919590:ios:ea2c616cb7cbb352dd51e7',
    messagingSenderId: '855172919590',
    projectId: 'inventory-4fd72',
    storageBucket: 'inventory-4fd72.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGw3ZZbfDs4Ke4WeHVXiXrK65J493NWw',
    appId: '1:855172919590:ios:ea2c616cb7cbb352dd51e7',
    messagingSenderId: '855172919590',
    projectId: 'inventory-4fd72',
    storageBucket: 'inventory-4fd72.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzYOBYSBK4ooA-oygV50V9bZA6gW5h9w0',
    appId: '1:855172919590:web:cedeb6df9ebe7d22dd51e7',
    messagingSenderId: '855172919590',
    projectId: 'inventory-4fd72',
    authDomain: 'inventory-4fd72.firebaseapp.com',
    storageBucket: 'inventory-4fd72.firebasestorage.app',
    measurementId: 'G-XPL4KGLYXG',
  );
}
